# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170327_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.TextField(blank=True, null=True, verbose_name='Цвета'),
        ),
    ]
